// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9pK0qnV8UEbgUC1Ekyw-UD1NVErE2chY',
    appId: '1:540987181636:web:34e56d763b4f927ff08a11',
    messagingSenderId: '540987181636',
    projectId: 'instaclone-c4bac',
    authDomain: 'instaclone-c4bac.firebaseapp.com',
    storageBucket: 'instaclone-c4bac.appspot.com',
    measurementId: 'G-F6KEQ64TK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcfuFkP_riyjkfPcRAdyK3OkxCunFsmec',
    appId: '1:540987181636:android:018929b6eb38be9cf08a11',
    messagingSenderId: '540987181636',
    projectId: 'instaclone-c4bac',
    storageBucket: 'instaclone-c4bac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMssVwsqstC6T1rakuY31fkDOpDvPRY6M',
    appId: '1:540987181636:ios:ac5def4c0f4cba6bf08a11',
    messagingSenderId: '540987181636',
    projectId: 'instaclone-c4bac',
    storageBucket: 'instaclone-c4bac.appspot.com',
    iosClientId: '540987181636-4bj9kv42qrte5989lqhhdshgoku90069.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );
}
